version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pharmacy_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 132
      POSTGRES_DB: pharmacy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pharmacy_message_bus
    restart: unless-stopped
    ports:
      - "5672:5672"   # App port
      - "15672:15672" # Gui port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
