services:
  db:
    image: postgres:16-alpine
    container_name: pharmacy_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 132
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pharmacy_message_bus
    restart: unless-stopped
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth-api:
    build:
      context: ./services
      dockerfile: Auth/Auth.Api/dockerfile
    container_name: pharmacy_auth_api
    restart: unless-stopped
    ports:
      - "5001:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PharmacyAuthDb;Username=admin;Password=132
    depends_on:
      - db
      - rabbitmq

  inventory-api:
    build:
      context: ./services
      dockerfile: Inventory/Inventory.Api/dockerfile
    container_name: pharmacy_inventory_api
    restart: unless-stopped
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PharmacyInventoryDb;Username=admin;Password=132
    depends_on:
      - db
      - rabbitmq

  api-gateway:
    build:
      context: ./services
      dockerfile: ApiGateway/ApiGateway/dockerfile
    container_name: pharmacy_api_gateway
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address=http://auth-api:8080
      - ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address=http://inventory-api:8080
    depends_on:
      - auth-api
      - inventory-api
      
volumes:
  postgres_data:
  rabbitmq_data: